game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.index, name='index')
]

gettingstarted/urls.py
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

import hello.views as hello
import game.views as game
import study.views as study

from django.conf import settings
from django.conf.urls.static import static

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    path("", include('hello.urls'), name="hello"),
    path("game/", include('game.urls'), name="game"),
    path("study/", include('study.urls'), name="study"),
    path('img_process/', include('img_process.urls'), name='img_process'),
    path("uploadapp/", include('uploadapp.urls'), name="uploadapp"),
    path("abstrans/", include('abstrans.urls'), name="abstrans"),
    # 画像アップロード機能は作ってみたけど今の所いらない
    path('markdownx/', include('markdownx.urls')),
    path("db/", hello.db, name="db"),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hello/urls.py
from django.urls import path, include
from . import views


app_name = 'blog'

urlpatterns = [
        path('', views.index, name='index'),
        path('detail/<int:blog_id>/', views.detail, name='detail'),
]

study/urls.py
from django.urls import path
from . import views

app_name = "study"

urlpatterns = [
    path('', views.index, name='index')
]

hello/models.py
from django.db import models

from markdownx.models import MarkdownxField
from django.utils.safestring import mark_safe
from markdownx.utils import markdownify

class Greeting(models.Model):
    when = models.DateTimeField("date created", auto_now_add=True)


class Blog(models.Model):
    title = models.CharField('Title', max_length=50)
    text = MarkdownxField('Text')
    created_at = models.DateField('Create Date', auto_now_add=True)
    uppdated_at = models.DateField('Uppdate Date', auto_now = True)

    def get_text_markdownx(self):
        return mark_safe(markdownify(self.text))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blog'

hello/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Blog
from .models import Greeting

def index(request):
    blogs = Blog.objects.order_by('-id')
    context = {
        'blogs': blogs
    }
    return render(request, 'hello/index.html', context)

def detail(request, blog_id):
    blog_text = get_object_or_404(Blog, id=blog_id)
    context = {
        'blog_text': blog_text
    }
    return render(request, 'hello/detail.html', context)

# from .models import Greeting

# Create your views here.
# def index(request):
#     params = {
#         'title': 'Hello/Index',
#         'msg': 'This is sample page',
#         'goto': 'next',
#     }
#     # return HttpResponse('Hello from Python!')
#     return render(request, "hello/index.html", params)

# def next(request):
#     params = {
#         'title': 'Hello/Next',
#         'msg': 'This is another page',
#         'goto': 'index',
#     }
#     return render(request, 'hello/index.html', params)


def db(request):

    greeting = Greeting()
    greeting.save()

    greetings = Greeting.objects.all()

    return render(request, "hello/db.html", {"greetings": greetings})

hello/templates/hello/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <title>Blog</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}">
</head>
<body>
    <img src="{% static 'img/back.png' %}">
    <h2>
        <a href="{% url 'blog:index' %}">日記</a>
        <!-- <a href="{% url 'game:index' %}">ゲーム</a> -->
        <!-- <a href="{% url 'study:index' %}">勉強内容</a> -->
    </h2>
    <h1>kan-nanのブログ</h1>
    <p>
        情報系の学部の大学院生になるわけだしブログでも作ってみるかぁってことで
        Heroku+django(python)で作り始めました！
        頑張って更新切らさないように頑張ります！<br>
        ブログ作り自体の日記とか勉強したこととかを乗せていければなって思います！
        ページの下の方に他の発信媒体のリンク乗せてるのでそちらも是非！

    </p>
    {% block content %}
    {% endblock %}
    <h2>リンク！</h2>
    <h3>
        <a href="https://twitter.com/Booo49357633">Twitter</a>
        <a href="https://github.com/kan-nan-sohta/">Github</a>
    </h3>

    <a class="twitter-timeline" href="https://twitter.com/Booo49357633?ref_src=twsrc%5Etfw">Tweets by Booo49357633</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</body>
</html>

hello/templates/hello/db.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container">


<h2>Page View Report</h2>


<ul>

{% for greeting in greetings %}
    <li>{{ greeting.when }}</li>
{% endfor %}

</ul>

</div>

{% endblock %}

hello/templates/hello/detail.html
{% extends 'hello/base.html' %}

{% block content %}

    <div class="detail_field">
        <h1>{{ blog_text.title }}</h1>
        <p>{{ blog_text.updated_at }}</p>
        <div class="markdownx">
            {{ blog_text.get_text_markdownx | safe }}<hr />
            </br>
        </div>
        <a href="{% url 'blog:index' %}">トップページに戻る</a>
    </div>

{% endblock %}

hello/templates/hello/index.html
{% extends 'hello/base.html' %}

{% block content %}

    <h1>日記一覧</h1>
    <br>
    {% for blog in blogs %}
        <ul>
            <li>
                {{ blog.created_at }}
                {{ blog.title }}
                <a href="{% url 'blog:detail' blog_id=blog.id %}">詳細</a>
            </li>
        </ul>
    {% endfor %}

{% endblock %}

<!-- {% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{title}}</title>
        <link rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            crossorigin="anonymous">
    </head>
    <body class="contriner">
        <h1 class="display-4 text-primary mb-4">{{title}}</h1>
        <p class="h5">{{msg}}</p>
        <p class="h6"><a href="{% url goto %}">{{goto}}</a></p>
    </body>
</html> -->